server:
  port: ${KK_SERVER_PORT:30119}
  servlet:
    context-path: ${KK_CONTEXT_PATH:/}
    encoding:
      charset: utf-8
  compression:
    enable: true
    min-response-size: 2048
    mime-types:
      - application/javascript
      - text/css
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
      - font/woff
      - application/font-woff
      - font/eot
      - image/svg+xml
      - image/x-icon

# spring 配置
spring:
  application:
    name: alinesno-infra-base-fileshow-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_base_fileshow_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  freemarker:
    template-loader-path: classpath:/pages/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  devtools:
    restart:
      enabled: true

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.base.fileshow.entity;
  database:
    type: mysql
  index:
    prefix: alinesno_base_fileshow_idx_
  unique:

# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key: